Repository bitcoindevkit/bdk-ffi, pull requests merged in 2022-08, with the labels that each got.

#182 Fix bdk-python link in readme
  README.md
Labels: documentation

#154 Add child key pair generation api
  CHANGELOG.md
  src/bdk.udl
  src/lib.rs
Labels: enhancement, summer-of-bitcoin

#184 Add `get_height` and `get_block_hash` methods on blockchain
  CHANGELOG.md
  src/bdk.udl
  src/lib.rs
Labels: enhancement

#186 Add tx builder set recipients
  CHANGELOG.md
  src/bdk.udl
  src/lib.rs
Labels: enhancement

#171 Add documentation
  src/lib.rs
Labels: documentation
