Repository bitcoindevkit/bdk-ffi, pull requests merged in 2023-04, with the labels that each got.

#335 Use version 21 of the Android NDK in the CI test, build, and publish workflows
  .github/workflows/publish-android.yaml
  .github/workflows/test-android.yaml
Labels: CI

#334 Add PartiallySignedTransaction.json_serialize() function
  api-docs/kotlin/src/main/kotlin/org/bitcoindevkit/bdk.kt
  bdk-ffi/src/bdk.udl
  bdk-ffi/src/psbt.rs
Labels: enhancement

#349 Update bdk-jvm README build instructions
  bdk-jvm/README.md
Labels: documentation

#351 Fix Python libraries' names to prepare for releasing
  .github/workflows/publish-python.yaml
  .github/workflows/test-python.yaml
  bdk-python/setup.py
Labels: CI, language: python
